### ISSUE TITLE
Restart processes upon error

### ISSUE THREAD

**Issue by Danappelxx** [jakeheis/Flock#1]
It would be quite useful to automatically reboot processes that exited with a non-zewo exit code in order to achieve better uptime. Naturally it would be opt-in.

**Comment by jakeheis** [comment]
Just to be clear, are you suggesting that instead of daemonizing processes using `nohup` (as ZewoFlock and company currently do), Flock should integrate with `systemd` and/or related tools to automatically restart processes on failure?

If so, I think it's a smart idea and should be pursued in the server specific Flock packages (like ZewoFlock) rather than the general Flock package itself

**Comment by Danappelxx** [comment]
Why do you think so? Swift applications have a nasty tendency to crash with no way to recover (optional unwrap, index-out-of-bounds, fatalerror). I would say its pretty vital for a service like Flock that manages your application to restart it if that happens.

**Comment by jakeheis** [comment]
My reasoning was essentially that, as of right now, Flock isn't actually in charge of starting any processes, be it through `nohup` or `systemd`; it delegates that work to ZewoFlock and the like. I could see value in centralizing this functionality in Flock though, as you're suggesting, since I would guess that regardless of Swift server library this functionality would be desired

**Comment by jakeheis** [comment]
I decided to include `systemd` functionality within Flock itself, as you suggested, and then allow servers from within their own packages to take advantage of this functionality. VaporFlock and ZewoFlock both do so now

**Comment by Danappelxx** [comment]
Didn't see this until now - awesome! Thanks for being so responsive :)
