### ISSUE TITLE
Login as non-sudo user

### ISSUE THREAD

**Issue by jdmcd** [jakeheis/Flock#5]
Right now, Flock requires a sudo account on the server to install into the directory. This could be unsafe, since AWS suggests going through the `ubuntu` account, which does not default to sudo. Are there any ways around this?

**Comment by krystofbe** [comment]
Seems hardly possible. Flock uses supervisord which requires you to be a privileged user. Also, `flock tools` uses `apt-get install `that also has to be run by a privileged user.

>  Ensure that the supervisord configuration file cannot be read from or written to by unprivileged users and that all files installed by the supervisor package have “sane” file permission protection settings. 
http://supervisord.org/running.html

**Comment by jdmcd** [comment]
Those were my thoughts too, wasn't sure if there was a workaround that was possible or not.

**Comment by jakeheis** [comment]
I suspect that `flock tools` will have to be run by a privileged user due to the `apt-get` call as @krystofbe suggests, but I suspect it might be possible to make `flock deploy` work when ran under an unprivileged user. https://coffeeonthekeyboard.com/using-supervisorctl-with-linux-permissions-but-without-root-or-sudo-977/ looks promising, but I haven't had time to look into it in depth yet

**Comment by jakeheis** [comment]
eb24630fe5ca3465b51d11e0fceafc61e4525be4 resolves this. `flock tools` still requires sudo, but `flock deploy` will now work without sudo

**Comment by jdmcd** [comment]
🎉  Thank you!
